### signup
POST http://localhost:5000/signup
Content-Type: application/json

{
    "name": "Fernanda",
    "nickname": "letscode",
    "email": "letscode@gmail.com",
   	"password": "lets@123"
    
}

### login
POST   http://localhost:5000/login
Content-Type: application/json

{
    "nickname": "letscode",
    "password": "lets@123"
}

### Create Card
POST http://localhost:5000/cards
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiZGJkY2U4LWZhZGEtNDdmNy05ZmQ1LWNiOWE1OTg5ZDcwMyIsIm5pY2tuYW1lIjoibGV0c2NvZGUiLCJpYXQiOjE2MTYyNzExNTMsImV4cCI6MTYxNjM1NzU1M30.WMxkDusHLJDwxLVBQCqzwlOmQFbkLK0pg6o3Csf_58I

{
    "subtitle":"para alterar o list",
    "content":"Testando alteração de list"
}

### Get Cards
GET  http://localhost:5000/cards
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiZGJkY2U4LWZhZGEtNDdmNy05ZmQ1LWNiOWE1OTg5ZDcwMyIsIm5pY2tuYW1lIjoibGV0c2NvZGUiLCJpYXQiOjE2MTYyNzExNTMsImV4cCI6MTYxNjM1NzU1M30.WMxkDusHLJDwxLVBQCqzwlOmQFbkLK0pg6o3Csf_58I



### Update Card
PUT  http://localhost:5000/cards/be33a913-041f-46f9-8d32-5608f88c8f5d
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiZGJkY2U4LWZhZGEtNDdmNy05ZmQ1LWNiOWE1OTg5ZDcwMyIsIm5pY2tuYW1lIjoibGV0c2NvZGUiLCJpYXQiOjE2MTYyNzExNTMsImV4cCI6MTYxNjM1NzU1M30.WMxkDusHLJDwxLVBQCqzwlOmQFbkLK0pg6o3Csf_58I


{
    "subtitle":"  Para testar a alteração de list",
    "content":"Alterando o list"
}

### Delete Card
DELETE   http://localhost:5000/cards/e0e2bbd9-e72a-4439-ae37-ae2c08e14fd1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiZGJkY2U4LWZhZGEtNDdmNy05ZmQ1LWNiOWE1OTg5ZDcwMyIsIm5pY2tuYW1lIjoibGV0c2NvZGUiLCJpYXQiOjE2MTYxMjAwMTgsImV4cCI6MTYxNjIwNjQxOH0.cV_R8QERp3egiqT9ueAlnuw_DB_-XiSq8bHBL7AtWbc



### Update Card
PUT  http://localhost:5000/cards/list/be33a913-041f-46f9-8d32-5608f88c8f5d
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiZGJkY2U4LWZhZGEtNDdmNy05ZmQ1LWNiOWE1OTg5ZDcwMyIsIm5pY2tuYW1lIjoibGV0c2NvZGUiLCJpYXQiOjE2MTYyNzExNTMsImV4cCI6MTYxNjM1NzU1M30.WMxkDusHLJDwxLVBQCqzwlOmQFbkLK0pg6o3Csf_58I


{
    "list":"Doing"
    
}