### signup
POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "name": "Fernanda",
    "nickname": "letscode",
    "email": "letscode@gmail.com",
   	"password": "lets@123"
    
}

### login
POST   http://localhost:5000/user/login
Content-Type: application/json

{
    "nickname": "letscode",
    "password": "lets@123"
}

### Create Card
POST http://localhost:5000/card/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRiMzJmZWY2LTdkZjgtNDQyMi04YmU3LWFlNmY2ZjQ0MzY2MyIsIm5pY2tuYW1lIjoibGV0c2NvZGUiLCJpYXQiOjE2MTU5NDUxMDgsImV4cCI6MTYxNjAzMTUwOH0.Q2Ls0drhQ5CdIG4xoaVDvh1dDs4Ndb9q0tFd4e0ci_E

{
    "subtitle":"",
    "content":"Testando a criação de outro card"
}

### Update Card
PUT  http://localhost:5000/card/update/9eec27ec-8589-4567-a234-7ce1a977e3fe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRiMzJmZWY2LTdkZjgtNDQyMi04YmU3LWFlNmY2ZjQ0MzY2MyIsIm5pY2tuYW1lIjoibGV0c2NvZGUiLCJpYXQiOjE2MTU5NDg3NDQsImV4cCI6MTYxNjAzNTE0NH0.6106lEtdqmi3IHctvGE8k5AuTHjntWptTvCh42bG57U

{
    "subtitle":" criando 2º card",
    "content":"Testando a alteração de 2º card"
}

### Delete Card
DELETE   http://localhost:5000/card/delete/9063ffa2-dd79-4007-a28c-b3cb241218eb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRiMzJmZWY2LTdkZjgtNDQyMi04YmU3LWFlNmY2ZjQ0MzY2MyIsIm5pY2tuYW1lIjoibGV0c2NvZGUiLCJpYXQiOjE2MTU5NDg3NDQsImV4cCI6MTYxNjAzNTE0NH0.6106lEtdqmi3IHctvGE8k5AuTHjntWptTvCh42bG57U